<x-filament-panels::page>
    <div class="grid gap-4" data-office-finance-funding>
        @if($canCreate)<x-filament::section heading="Funding Received" description="Internal Dubai funding is not revenue. Actual PKR received is authoritative for Office balance." compact>
            <form wire:submit="postFunding" class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                <label class="grid gap-1 text-sm"><span>Funding Date</span><x-filament::input.wrapper><x-filament::input type="date" wire:model="fundingDate" /></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-sm"><span>Source / From</span><x-filament::input.wrapper><x-filament::input wire:model="source" /></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-sm"><span>AED Amount</span><x-filament::input.wrapper prefix="AED"><x-filament::input type="number" step="0.01" wire:model.live.debounce.250ms="aedAmount" /></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-sm"><span>Exchange Rate PKR/AED</span><x-filament::input.wrapper><x-filament::input type="number" step="0.000001" wire:model.live.debounce.250ms="exchangeRate" /></x-filament::input.wrapper></label>
                <div class="rounded-xl border border-gray-200 p-3 dark:border-white/10"><div class="text-xs text-gray-500">Calculated PKR</div><div class="font-bold">PKR {{ number_format((float)$this->calculatedPkr,2) }}</div></div>
                <label class="grid gap-1 text-sm"><span>Actual PKR Received</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model.live.debounce.250ms="actualPkr" /></x-filament::input.wrapper></label>
                <div class="rounded-xl border border-gray-200 p-3 dark:border-white/10"><div class="text-xs text-gray-500">Difference</div><div class="font-bold">PKR {{ number_format((float)$this->difference,2) }}</div></div>
                <label class="grid gap-1 text-sm"><span>Bank / FX Charges</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model="charges" /></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-sm"><span>Receiving Account</span><x-filament::input.wrapper><x-filament::input.select wire:model="accountId"><option value="">Select</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-sm"><span>Transfer Reference</span><x-filament::input.wrapper><x-filament::input wire:model="transferReference" /></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-sm md:col-span-2"><span>Note</span><x-filament::input.wrapper><x-filament::input wire:model="note" /></x-filament::input.wrapper></label>
                <div class="flex items-end justify-end xl:col-span-4"><x-filament::button type="submit" wire:loading.attr="disabled">Post Funding</x-filament::button></div>
            </form>
        </x-filament::section>@endif
        <x-filament::section heading="Funding History" compact><div class="overflow-x-auto"><table class="w-full min-w-[64rem] text-sm"><thead><tr><th>Date</th><th>Reference</th><th>Source</th><th class="text-right">AED</th><th class="text-right">Rate</th><th class="text-right">Calculated PKR</th><th class="text-right">Actual PKR</th><th class="text-right">Difference</th><th>Account</th><th>Status</th></tr></thead><tbody>@forelse($funding as $row)<tr class="border-t border-gray-100 dark:border-white/5"><td>{{ $row->transaction_date->format('d M Y') }}</td><td>{{ $row->reference }}</td><td>{{ $row->funding_source }}</td><td class="text-right">{{ number_format((float)$row->aed_amount,2) }}</td><td class="text-right">{{ number_format((float)$row->exchange_rate_pkr_per_aed,6) }}</td><td class="text-right">{{ number_format((float)$row->calculated_pkr_amount,2) }}</td><td class="text-right">{{ number_format((float)$row->amount_pkr,2) }}</td><td class="text-right">{{ number_format((float)bcsub($row->amount_pkr,$row->calculated_pkr_amount,2),2) }}</td><td>{{ $row->account->name }}</td><td>{{ str($row->status)->title() }}</td></tr>@empty<tr><td colspan="10" class="py-8 text-center text-gray-500">No funding has been posted.</td></tr>@endforelse</tbody></table></div><div class="mt-3">{{ $funding->links() }}</div></x-filament::section>
    </div>
</x-filament-panels::page>
