<x-filament-panels::page>
    <div class="grid gap-4" data-office-finance-loans>
        @if($canManage)<x-filament::section heading="Employee Loan Given" description="Posting creates one immutable Money Out transaction and linked Employee Loan atomically." compact><form wire:submit="createLoan" class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            <label class="grid gap-1 text-sm"><span>Employee</span><x-filament::input.wrapper><x-filament::input.select wire:model="employeeId"><option value="">Select</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} · {{ $employee->employee_id }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>
            <label class="grid gap-1 text-sm"><span>Date</span><x-filament::input.wrapper><x-filament::input type="date" wire:model="loanDate" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Amount PKR</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model="loanAmount" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Paid Through</span><x-filament::input.wrapper><x-filament::input.select wire:model="loanAccountId"><option value="">Select</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>
            <label class="grid gap-1 text-sm md:col-span-2"><span>Reason</span><x-filament::input.wrapper><x-filament::input wire:model="loanReason" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Reference</span><x-filament::input.wrapper><x-filament::input wire:model="loanExternalReference" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Note</span><x-filament::input.wrapper><x-filament::input wire:model="loanNote" /></x-filament::input.wrapper></label>
            <div class="flex justify-end xl:col-span-4"><x-filament::button type="submit" wire:loading.attr="disabled">Post Employee Loan</x-filament::button></div>
        </form></x-filament::section>@endif

        @if($canManage && $repaymentLoanId)<x-filament::section heading="Record Repayment" description="A repayment creates a separate Money In transaction; the original loan remains unchanged." compact><form wire:submit="recordRepayment" class="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label class="grid gap-1 text-sm"><span>Date</span><x-filament::input.wrapper><x-filament::input type="date" wire:model="repaymentDate" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Amount PKR</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model="repaymentAmount" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Received Into</span><x-filament::input.wrapper><x-filament::input.select wire:model="repaymentAccountId"><option value="">Select</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label><label class="grid gap-1 text-sm"><span>Reference</span><x-filament::input.wrapper><x-filament::input wire:model="repaymentReference" /></x-filament::input.wrapper></label><label class="grid gap-1 text-sm md:col-span-3"><span>Note</span><x-filament::input.wrapper><x-filament::input wire:model="repaymentNote" /></x-filament::input.wrapper></label><div class="flex items-end justify-end"><x-filament::button type="submit">Record Repayment</x-filament::button></div></form></x-filament::section>@endif

        <x-filament::section heading="Employee Loans" compact><div class="overflow-x-auto"><table class="w-full min-w-[56rem] text-sm"><thead><tr><th>Employee</th><th>Reference</th><th>Date</th><th>Account</th><th class="text-right">Original Loan</th><th class="text-right">Repaid</th><th class="text-right">Outstanding</th><th>Status</th>@if($canManage)<th>Action</th>@endif</tr></thead><tbody>@forelse($loans as $loan)<tr class="border-t border-gray-100 dark:border-white/5"><td>{{ $loan->employee->name }}</td><td>{{ $loan->transaction->reference }}</td><td>{{ $loan->transaction->transaction_date->format('d M Y') }}</td><td>{{ $loan->transaction->account->name }}</td><td class="text-right">PKR {{ number_format((float)$loan->transaction->amount_pkr,2) }}</td><td class="text-right">PKR {{ number_format((float)$loan->repaid_amount,2) }}</td><td class="text-right">PKR {{ number_format((float)$loan->outstanding_amount,2) }}</td><td><x-filament::badge>{{ $loan->status->label() }}</x-filament::badge></td>@if($canManage)<td>@if(!in_array($loan->status->value,['repaid','voided'],true))<x-filament::button size="xs" wire:click="prepareRepayment({{ $loan->id }})">Record Repayment</x-filament::button>@endif</td>@endif</tr>@empty<tr><td colspan="9" class="py-8 text-center text-gray-500">No employee loans have been posted.</td></tr>@endforelse</tbody></table></div><div class="mt-3">{{ $loans->links() }}</div></x-filament::section>
    </div>
</x-filament-panels::page>
