<x-filament-panels::page>
    <div class="grid min-w-0 gap-4" data-office-finance-cashbook>
        @if($canCreate)
            <x-filament::section :heading="$expenseShortcut ? 'Add Pakistan Office Expense' : 'New Transaction'" :description="$expenseShortcut ? 'Use this for Pakistan office expenses recorded in PKR.' : 'Post a controlled PKR cashbook entry. Only fields relevant to the selected type are shown.'" compact>
                <form wire:submit="postTransaction" class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                    @if(!$expenseShortcut)<label class="grid gap-1 text-sm"><span>Type</span><x-filament::input.wrapper><x-filament::input.select wire:model.live="transactionType">@foreach($types as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>@else<div class="flex items-end"><x-filament::badge color="success">Currency: PKR</x-filament::badge></div>@endif
                    <label class="grid gap-1 text-sm"><span>Date</span><x-filament::input.wrapper><x-filament::input type="date" wire:model="transactionDate" /></x-filament::input.wrapper>@error('transactionDate')<span class="text-danger-600">{{ $message }}</span>@enderror</label>
                    <label class="grid gap-1 text-sm"><span>Account</span><x-filament::input.wrapper><x-filament::input.select wire:model="accountId"><option value="">Select active account</option>@foreach($accounts->where('active',true) as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper>@error('officeFinanceAccountId')<span class="text-danger-600">{{ $message }}</span>@enderror</label>
                    @if($transactionType === 'expense')<label class="grid gap-1 text-sm"><span>Category</span><x-filament::input.wrapper><x-filament::input.select wire:model="category"><option value="">Select</option>@foreach($categories as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>@endif
                    @if(in_array($transactionType,['expense','employee_loan_given'],true))<div class="grid min-w-0 gap-1 text-sm"><span>Employee {{ $transactionType === 'expense' ? '(optional)' : '' }}</span><x-filament::input.wrapper prefix-icon="heroicon-m-magnifying-glass"><x-filament::input wire:model.live.debounce.300ms="employeeSearch" placeholder="Type 2+ characters" /></x-filament::input.wrapper><x-filament::input.wrapper><x-filament::input.select wire:model="employeeId"><option value="">Select Employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} · {{ $employee->employee_id }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></div>@endif
                    @if($transactionType === 'employee_loan_repayment')<label class="grid gap-1 text-sm"><span>Employee Loan</span><x-filament::input.wrapper><x-filament::input.select wire:model="loanId"><option value="">Select open loan</option>@foreach($loans as $loan)<option value="{{ $loan->id }}">{{ $loan->employee->name }} · {{ $loan->transaction->reference }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>@endif
                    @if($transactionType === 'funding_received')
                        <label class="grid gap-1 text-sm"><span>Source / From</span><x-filament::input.wrapper><x-filament::input wire:model="fundingSource" /></x-filament::input.wrapper></label>
                        <label class="grid gap-1 text-sm"><span>AED Amount</span><x-filament::input.wrapper prefix="AED"><x-filament::input type="number" step="0.01" wire:model.live.debounce.300ms="aedAmount" /></x-filament::input.wrapper></label>
                        <label class="grid gap-1 text-sm"><span>Rate PKR/AED</span><x-filament::input.wrapper><x-filament::input type="number" step="0.000001" wire:model.live.debounce.300ms="exchangeRate" /></x-filament::input.wrapper></label>
                        <div class="rounded-xl border border-gray-200 p-3 text-sm dark:border-white/10"><div class="text-xs text-gray-500">Calculated PKR</div><strong>PKR {{ number_format((float)$this->calculatedPkr,2) }}</strong></div>
                        <label class="grid gap-1 text-sm"><span>Actual PKR Received</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model="amountPkr" /></x-filament::input.wrapper></label>
                        <label class="grid gap-1 text-sm"><span>Bank / FX Charges</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model="fxCharges" /></x-filament::input.wrapper></label>
                    @else
                        <label class="grid gap-1 text-sm"><span>Amount PKR</span><x-filament::input.wrapper prefix="PKR"><x-filament::input type="number" step="0.01" wire:model="amountPkr" /></x-filament::input.wrapper>@error('amountPkr')<span class="text-danger-600">{{ $message }}</span>@enderror</label>
                    @endif
                    @if($transactionType === 'adjustment' && $owner)<label class="grid gap-1 text-sm"><span>Direction</span><x-filament::input.wrapper><x-filament::input.select wire:model="direction"><option value="in">Money In</option><option value="out">Money Out</option></x-filament::input.select></x-filament::input.wrapper></label><label class="grid gap-1 text-sm md:col-span-2"><span>Adjustment Reason</span><x-filament::input.wrapper><x-filament::input wire:model="adjustmentReason" /></x-filament::input.wrapper></label>@endif
                    <label class="grid gap-1 text-sm md:col-span-2"><span>Description / Reason</span><x-filament::input.wrapper><x-filament::input wire:model="description" /></x-filament::input.wrapper></label>
                    <label class="grid gap-1 text-sm"><span>External Reference</span><x-filament::input.wrapper><x-filament::input wire:model="externalReference" /></x-filament::input.wrapper></label>
                    <label class="grid gap-1 text-sm"><span>Note</span><x-filament::input.wrapper><x-filament::input wire:model="note" /></x-filament::input.wrapper></label>
                    <div class="flex items-end justify-end xl:col-span-4"><x-filament::button type="submit" wire:loading.attr="disabled" wire:target="postTransaction"><span wire:loading.remove wire:target="postTransaction">{{ $expenseShortcut ? 'Add Expense' : 'Post Transaction' }}</span><span wire:loading wire:target="postTransaction">Posting...</span></x-filament::button></div>
                </form>
            </x-filament::section>
        @endif

        <x-filament::section :heading="$expenseShortcut ? 'Pakistan Office Expenses' : 'Cashbook'" compact>
            <div class="mb-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
                <label class="grid gap-1 text-xs"><span>From</span><x-filament::input.wrapper><x-filament::input type="date" wire:model="from" /></x-filament::input.wrapper></label><label class="grid gap-1 text-xs"><span>To</span><x-filament::input.wrapper><x-filament::input type="date" wire:model="to" /></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-xs"><span>Type</span><x-filament::input.wrapper><x-filament::input.select wire:model="typeFilter"><option value="">All</option>@foreach($types as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-xs"><span>Account</span><x-filament::input.wrapper><x-filament::input.select wire:model="accountFilter"><option value="">All</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-xs"><span>Category</span><x-filament::input.wrapper><x-filament::input.select wire:model="categoryFilter"><option value="">All</option>@foreach($categories as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></label>
                <div class="grid min-w-0 gap-1 text-xs"><span>Employee</span><x-filament::input.wrapper><x-filament::input wire:model.live.debounce.300ms="employeeSearch" placeholder="Search name or Employee ID" /></x-filament::input.wrapper><x-filament::input.wrapper><x-filament::input.select wire:model="employeeFilter"><option value="">All authorized</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</x-filament::input.select></x-filament::input.wrapper></div>
                <label class="grid gap-1 text-xs"><span>Status</span><x-filament::input.wrapper><x-filament::input.select wire:model="statusFilter"><option value="">All</option><option value="posted">Posted</option><option value="voided">Voided</option></x-filament::input.select></x-filament::input.wrapper></label>
                <label class="grid gap-1 text-xs xl:col-span-2"><span>Search</span><x-filament::input.wrapper><x-filament::input wire:model="search" placeholder="Reference, description, employee, source" /></x-filament::input.wrapper></label>
                <div class="flex items-end"><x-filament::button size="sm" wire:click="applyFilters">Apply</x-filament::button></div>
            </div>
            <div class="overflow-x-auto"><table class="w-full min-w-[72rem] text-sm"><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Category / Employee / Source</th><th>Description</th><th>Account</th><th class="text-right">Money In</th><th class="text-right">Money Out</th><th>Created By</th><th>Status</th>@if($canVoid)<th>Correction</th>@endif</tr></thead><tbody>@forelse($transactions as $row)<tr class="border-t border-gray-100 dark:border-white/5"><td>{{ $row->transaction_date->format('d M Y') }}</td><td class="font-medium">{{ $row->reference }}</td><td>{{ $row->transaction_type->label() }}</td><td>{{ $row->category?->label() ?? $row->employee?->name ?? $row->funding_source ?? '—' }}</td><td>{{ str($row->description)->limit(45) }}</td><td>{{ $row->account->name }}</td><td class="text-right">{{ $row->direction === 'in' ? 'PKR '.number_format((float)$row->amount_pkr,2) : '—' }}</td><td class="text-right">{{ $row->direction === 'out' ? 'PKR '.number_format((float)$row->amount_pkr,2) : '—' }}</td><td>{{ $row->createdBy->name }}</td><td><x-filament::badge :color="$row->status === 'posted' ? 'success' : 'gray'">{{ str($row->status)->title() }}</x-filament::badge></td>@if($canVoid)<td>@if($row->status === 'posted')<div class="flex min-w-[16rem] gap-1"><x-filament::input.wrapper><x-filament::input wire:model="voidReasons.{{ $row->id }}" placeholder="Mandatory void reason" /></x-filament::input.wrapper><x-filament::button size="xs" color="danger" wire:click="voidTransaction({{ $row->id }})">Void</x-filament::button></div>@error('voidReasons.'.$row->id)<div class="text-xs text-danger-600">{{ $message }}</div>@enderror@endif</td>@endif</tr>@empty<tr><td colspan="11" class="py-8 text-center text-gray-500">No Cashbook transactions match the selected filters.</td></tr>@endforelse</tbody></table></div>
            <div class="mt-3">{{ $transactions->links() }}</div>
        </x-filament::section>
    </div>
</x-filament-panels::page>
