<!doctype html><html lang="en"><head><meta charset="utf-8"><style>@page{margin:24px 30px}body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#182c46}.watermark{position:fixed;left:25px;width:480px;text-align:center;font-size:28px;font-weight:bold;line-height:1.5;color:#182c46;opacity:.08;transform:rotate(-30deg);z-index:-1}.watermark-top{top:140px}.watermark-middle{top:380px}.watermark-bottom{top:620px}.header{width:100%;border-bottom:3px solid #e28d24;margin-bottom:14px}.header td{vertical-align:middle}.logo{width:150px}.title{font-size:20px;font-weight:bold}h2{font-size:13px;margin:12px 0 5px}table{width:100%;border-collapse:collapse}td,th{padding:5px;text-align:left;border-bottom:1px solid #dce3eb}th{background:#eef3f8}.group{page-break-inside:avoid}.summary{background:#f2f6fa;padding:12px}.qr{width:115px;background:#fff;padding:8px}.footer{font-size:9px;color:#546273}</style></head><body>
@foreach(['top', 'middle', 'bottom'] as $position)<div class="watermark watermark-{{ $position }}">TECH POINT ZONE<br>VERIFIED QC<br>{{ $snapshot['reference'] }} · v{{ $certificate->version }}</div>@endforeach
<table class="header"><tr><td><img class="logo" src="{{ $logo }}" alt="Tech Point Zone"></td><td class="title">QUALITY CONTROL CERTIFICATE</td></tr></table>
@if(! $isCurrent)<p style="border:2px solid #ab3b24;padding:10px"><strong>HISTORICAL / SUPERSEDED - NOT CURRENT QC CERTIFICATION</strong></p>@endif
<div class="summary"><strong>{{ $snapshot['reference'] }} · Version {{ $certificate->version }}</strong><br>{{ app(\App\Services\BusinessTimezone::class)->format($snapshot['certified_at']) }}<br><h2>{{ $snapshot['product']['title'] }}</h2>SKU {{ $snapshot['product']['sku'] }} · S/N {{ $snapshot['serial'] }}<br>Condition {{ ucfirst($snapshot['product']['condition']) }} · Grade {{ $snapshot['grade'] }}<br><strong>{{ count($snapshot['checks']) }} applicable checks / {{ count($snapshot['checks']) }} passed</strong></div>
<h2>Final Tested Configuration</h2><p>@include('qc.final-specs', ['final' => $snapshot['final']])</p>
<p>Original configuration: {{ $snapshot['original']['cpu'] ?? '—' }} · {{ $snapshot['original']['ram'] ?? '—' }} · {{ $snapshot['original']['storage'] ?? '—' }}</p>
@if($snapshot['requested'])<p>Customer required: {{ $snapshot['requested']['display_name'] ?? $snapshot['requested']['special_requirement'] ?? 'Upgraded configuration' }} @isset($snapshot['requested']['target_ram_mb']) · {{ $snapshot['requested']['target_ram_mb'] / 1024 }} GB RAM @endisset @isset($snapshot['requested']['target_storage_total_gb']) · {{ $snapshot['requested']['target_storage_total_gb'] }} GB Storage @endisset</p>@endif
@foreach(collect($snapshot['checks'])->groupBy('group') as $group => $checks)<table style="page-break-inside:avoid"><tr><td style="padding:0;border:0"><h2>{{ $group }}</h2><table><tr><th>Check</th><th>Verified result</th></tr>@foreach($checks as $check)<tr><td>{{ $check['label'] }}</td><td>{{ $check['detail'] }} @if($check['measurement'] !== null)({{ $check['measurement'] }})@endif</td></tr>@endforeach</table></td></tr></table>@endforeach
@if($snapshot['remarks'])<p>{{ $snapshot['remarks'] }}</p>@endif
<p>Evidence summary: {{ count($snapshot['evidence']) }} customer-visible proofs retained with server upload timestamps.</p>
<p class="footer">This certificate is electronically issued by Tech Point Zone. Alterations invalidate this document. Scan the QR code or verify the QC ID online to confirm authenticity.</p>
<p class="footer">Valid only when the QR code resolves to the matching TPZ QC ID and certificate version.</p>
<p class="footer">Certificate Fingerprint: <strong>{{ $fingerprint }}</strong> (visible identity reference, not a digital signature).</p>
<table><tr><td><strong>Inspected &amp; Certified by: {{ $snapshot['technician'] }}</strong><p>Electronically verified by TPZ ERP</p><p class="footer">Scan the QR to verify this certificate and view the watermarked device evidence.</p></td><td style="width:130px"><img class="qr" src="{{ $qr }}" alt="Verification QR"></td></tr></table>
</body></html>
