<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TPZ Verified Device</title><style>body{font-family:Arial,sans-serif;background:#f3f6fa;color:#172b46;margin:0}main{max-width:860px;margin:2rem auto;padding:24px;background:white;border-radius:16px}h1{line-height:1.25}.verified{color:#187747}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px}img{max-width:100%;height:auto}.evidence{border:1px solid #ddd;padding:10px;border-radius:10px}small{color:#526174}li{padding:4px 0}summary{cursor:pointer;font-weight:bold}</style></head><body><main>
<img src="{{ asset('branding/tech-point-zone-logo.png') }}" width="180" alt="Tech Point Zone"><p>VERIFIED DEVICE</p>
@if($certificate->isCurrent())<h2 class="verified">✓ QC VERIFIED</h2>@else<h2>Historical certificate - Version {{ $certificate->version }}</h2>@if($currentUrl !== app(\App\Services\Qc\QcDocumentService::class)->url($certificate))<a href="{{ $currentUrl }}">View current QC version</a>@else<p>Reinspection is in progress. This previous certificate is not current.</p>@endif @endif
<h1>{{ $snapshot['product']['title'] }}</h1><p>@include('qc.final-specs', ['final' => $snapshot['final']])</p>
<div class="grid"><p>Condition: <strong>{{ ucfirst($snapshot['product']['condition']) }}</strong><br>Grade: <strong>{{ $snapshot['grade'] }}</strong></p><p>QC Certificate: <strong>{{ $snapshot['reference'] }}</strong><br>Version {{ $certificate->version }}<br>{{ \Illuminate\Support\Carbon::parse($snapshot['certified_at'])->format('d M Y H:i T') }}</p></div>
<p>Serial / IMEI: {{ strlen($snapshot['serial']) > 6 ? substr($snapshot['serial'], 0, 3).'••••'.substr($snapshot['serial'], -3) : '••••' }}</p>
<h2>{{ count($snapshot['checks']) }} applicable checks · {{ count($snapshot['checks']) }} passed</h2>
<h2>Final Tested Configuration</h2><p>@include('qc.final-specs', ['final' => $snapshot['final']])</p>
@foreach(collect($snapshot['checks'])->groupBy('group') as $group => $checks)<details><summary>{{ $group }} · {{ $checks->count() }} passed</summary><ul>@foreach($checks as $check)<li>{{ $check['label'] }}: {{ $check['detail'] }} @if($check['measurement'] !== null)({{ $check['measurement'] }})@endif</li>@endforeach</ul></details>@endforeach
<h2>Verified Condition Evidence</h2><div class="grid">@foreach($evidence as $image)<figure class="evidence"><img loading="lazy" src="{{ route('qc.evidence.public', ['token' => $certificate->public_token, 'id' => $image->public_id]) }}" alt="{{ \App\Services\Qc\QcEvidenceService::KINDS[$image->kind] }}"><figcaption>{{ \App\Services\Qc\QcEvidenceService::KINDS[$image->kind] }}</figcaption></figure>@endforeach</div>
@if($snapshot['remarks'])<p>{{ $snapshot['remarks'] }}</p>@endif
<h3>Inspected &amp; Certified by: {{ $snapshot['technician'] }}</h3><p>Electronically verified by TPZ ERP</p>
</main></body></html>
