<x-filament-panels::page>
    <x-filament::section :heading="$editingScheduleId ? 'Configure Schedule Pattern' : 'Create Work Schedule'" compact>
        <form wire:submit="saveSchedule" class="space-y-4">
            <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
                <label class="space-y-1 text-sm"><span class="font-medium">Name</span><input wire:model="name" @disabled($editingScheduleId) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5">@error('name')<p class="text-danger-600">{{ $message }}</p>@enderror</label>
                <label class="space-y-1 text-sm"><span class="font-medium">Code</span><input wire:model="code" @disabled($editingScheduleId) placeholder="ALT_WEEKEND" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5">@error('code')<p class="text-danger-600">{{ $message }}</p>@enderror</label>
                <label class="space-y-1 text-sm"><span class="font-medium">Timezone</span><input wire:model="timezone" @disabled($editingScheduleId) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></label>
                <label class="space-y-1 text-sm"><span class="font-medium">Type</span><select wire:model="scheduleType" @disabled($editingScheduleId) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"><option value="standard">Standard</option><option value="alternative_weekend">Alternative Weekend</option><option value="custom">Custom</option></select></label>
                <label class="space-y-1 text-sm"><span class="font-medium">Rotation Weeks</span><input type="number" min="1" max="12" wire:model.live="cycleLengthWeeks" @disabled($editingScheduleId) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></label>
            </div>
            @error('schedule')<div class="text-sm text-danger-600">{{ $message }}</div>@enderror
            @error('days')<div class="text-sm text-danger-600">{{ $message }}</div>@enderror
            <div class="overflow-x-auto rounded-lg border border-gray-200 dark:border-white/10">
                <table class="w-full min-w-[850px] text-sm"><thead class="bg-gray-50 dark:bg-white/5"><tr><th class="px-3 py-2 text-left">Week</th><th class="px-3 py-2 text-left">Day</th><th class="px-3 py-2">Working</th><th class="px-3 py-2">Start</th><th class="px-3 py-2">End</th><th class="px-3 py-2">Break Start</th><th class="px-3 py-2">Break End</th><th class="px-3 py-2">Sunday earns Comp Off</th></tr></thead>
                    <tbody class="divide-y divide-gray-100 dark:divide-white/5">@foreach($days as $index => $day)<tr wire:key="schedule-day-{{ $index }}"><td class="px-3 py-2 text-center">{{ $day['cycle_week'] }}</td><td class="px-3 py-2 font-medium">{{ $weekdays[$day['weekday']] }}</td><td class="px-3 py-2 text-center"><input type="checkbox" wire:model.live="days.{{ $index }}.is_working_day" class="rounded border-gray-300"></td><td class="px-3 py-2"><input type="time" wire:model="days.{{ $index }}.expected_start_time" @disabled(! $day['is_working_day']) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></td><td class="px-3 py-2"><input type="time" wire:model="days.{{ $index }}.expected_end_time" @disabled(! $day['is_working_day']) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></td><td class="px-3 py-2"><input type="time" wire:model="days.{{ $index }}.break_start_time" @disabled(! $day['is_working_day']) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></td><td class="px-3 py-2"><input type="time" wire:model="days.{{ $index }}.break_end_time" @disabled(! $day['is_working_day']) class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></td><td class="px-3 py-2 text-center"><input type="checkbox" wire:model="days.{{ $index }}.earns_compensatory_off" @disabled(! $day['is_working_day'] || $day['weekday'] !== 0) class="rounded border-gray-300"></td></tr>@endforeach</tbody>
                </table>
            </div>
            <div class="flex justify-end"><x-filament::button type="submit">{{ $editingScheduleId ? 'Save Pattern' : 'Create Schedule' }}</x-filament::button></div>
        </form>
    </x-filament::section>

    <x-filament::section heading="Assign Schedule" compact>
        <form wire:submit="assignSchedule" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <label class="space-y-1 text-sm"><span class="font-medium">Schedule</span><select wire:model="assignmentScheduleId" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"><option value="">Select</option>@foreach($schedules->where('status',true) as $schedule)<option value="{{ $schedule->id }}">{{ $schedule->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm"><span class="font-medium">Assign To</span><select wire:model.live="assignmentTargetType" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"><option value="employee">Employee</option><option value="team">Team</option></select></label>
            @if($assignmentTargetType === 'employee')<label class="space-y-1 text-sm"><span class="font-medium">Employee</span><select wire:model="assignmentEmployeeId" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"><option value="">Select</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} · {{ $employee->employee_id }}</option>@endforeach</select>@error('assignmentEmployeeId')<p class="text-danger-600">{{ $message }}</p>@enderror</label>@else<label class="space-y-1 text-sm"><span class="font-medium">Team</span><select wire:model="assignmentTeamId" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"><option value="">Select</option>@foreach($teams as $team)<option value="{{ $team->id }}">{{ $team->name }}</option>@endforeach</select>@error('assignmentTeamId')<p class="text-danger-600">{{ $message }}</p>@enderror</label>@endif
            <label class="space-y-1 text-sm"><span class="font-medium">Effective From</span><input type="date" wire:model="assignmentEffectiveFrom" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></label>
            <label class="space-y-1 text-sm"><span class="font-medium">Effective To</span><input type="date" wire:model="assignmentEffectiveTo" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></label>
            <label class="space-y-1 text-sm lg:col-span-2"><span class="font-medium">Reason</span><input wire:model="assignmentReason" class="w-full rounded-lg border-gray-300 dark:border-white/10 dark:bg-white/5"></label>
            <div class="flex items-end"><x-filament::button type="submit" class="w-full">Assign Schedule</x-filament::button></div>
        </form>
    </x-filament::section>

    <div class="space-y-3">@foreach($schedules as $schedule)<x-filament::section compact><div class="flex flex-wrap items-center justify-between gap-3"><div><div class="flex items-center gap-2"><strong>{{ $schedule->name }}</strong><x-filament::badge :color="$schedule->status ? 'success' : 'gray'">{{ $schedule->status ? 'Active' : 'Inactive' }}</x-filament::badge></div><div class="text-sm text-gray-500">{{ $schedule->code }} · {{ str($schedule->schedule_type)->replace('_',' ')->title() }} · {{ $schedule->cycle_length_weeks }} week rotation · {{ $schedule->timezone }} · {{ $schedule->current_assignments_count }} current @if($schedule->ended_assignments_count > 0)· {{ $schedule->ended_assignments_count }} ended @endif</div></div><div class="flex gap-2"><x-filament::button size="xs" color="gray" wire:click="editPattern({{ $schedule->id }})">Configure Pattern</x-filament::button><x-filament::button size="xs" color="gray" wire:click="toggleStatus({{ $schedule->id }})">{{ $schedule->status ? 'Deactivate' : 'Activate' }}</x-filament::button></div></div>@if($schedule->assignments->isNotEmpty())<div class="mt-3 space-y-2">@foreach($schedule->assignments as $assignment)@php($ended = $assignment->effective_to?->isBefore(today()) ?? false)@php($endsToday = $assignment->effective_to?->isToday() ?? false)<div class="flex flex-wrap items-center gap-2"><x-filament::badge :color="$ended ? 'gray' : ($endsToday ? 'warning' : 'info')">{{ $assignment->employee ? 'Employee — '.$assignment->employee->name : 'Team — '.$assignment->team?->name }} · {{ $assignment->effective_from->format('d M Y') }}–{{ $assignment->effective_to?->format('d M Y') ?? 'Open' }}</x-filament::badge>@if($ended)<x-filament::badge color="gray">Ended</x-filament::badge>@elseif($endsToday)<x-filament::badge color="warning">Ends Today</x-filament::badge>@else{{ ($this->endAssignmentAction)(['assignmentId' => $assignment->id]) }}@endif</div>@endforeach</div>@endif</x-filament::section>@endforeach</div>
</x-filament-panels::page>
